// <auto-generated />
using System;
using GameForge.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameForge.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260820190957_AddQuestSystem")]
    partial class AddQuestSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameForge.API.Models.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CharacterClass")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Mana")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("GameForge.API.Models.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ItemId1")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ItemId1");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("GameForge.API.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttackBonus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefenseBonus")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("HealthRestore")
                        .HasColumnType("integer");

                    b.Property<int>("ManaRestore")
                        .HasColumnType("integer");

                    b.Property<int>("MaxStack")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AttackBonus = 5,
                            CreatedAt = new DateTime(2026, 8, 20, 19, 9, 55, 937, DateTimeKind.Utc).AddTicks(4987),
                            DefenseBonus = 0,
                            Description = "A weathered iron blade.",
                            HealthRestore = 0,
                            ManaRestore = 0,
                            MaxStack = 1,
                            Name = "Rusty Sword",
                            Rarity = 0,
                            Type = 0,
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            AttackBonus = 0,
                            CreatedAt = new DateTime(2026, 8, 20, 19, 9, 55, 938, DateTimeKind.Utc).AddTicks(31),
                            DefenseBonus = 12,
                            Description = "Sturdy steel breastplate.",
                            HealthRestore = 0,
                            ManaRestore = 0,
                            MaxStack = 1,
                            Name = "Iron Plate Armor",
                            Rarity = 1,
                            Type = 1,
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            AttackBonus = 150,
                            CreatedAt = new DateTime(2026, 8, 20, 19, 9, 55, 938, DateTimeKind.Utc).AddTicks(68),
                            DefenseBonus = 25,
                            Description = "Forged in ancient dragon fire.",
                            HealthRestore = 0,
                            ManaRestore = 0,
                            MaxStack = 1,
                            Name = "Dragon Slayer Blade",
                            Rarity = 4,
                            Type = 0,
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            AttackBonus = 0,
                            CreatedAt = new DateTime(2026, 8, 20, 19, 9, 55, 938, DateTimeKind.Utc).AddTicks(73),
                            DefenseBonus = 0,
                            Description = "Restores 50 hit points.",
                            HealthRestore = 50,
                            ManaRestore = 0,
                            MaxStack = 99,
                            Name = "Lesser Health Potion",
                            Rarity = 0,
                            Type = 2,
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            AttackBonus = 0,
                            CreatedAt = new DateTime(2026, 8, 20, 19, 9, 55, 938, DateTimeKind.Utc).AddTicks(538),
                            DefenseBonus = 0,
                            Description = "Restores 35 mana points.",
                            HealthRestore = 0,
                            ManaRestore = 35,
                            MaxStack = 99,
                            Name = "Mana Flask",
                            Rarity = 0,
                            Type = 2,
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            AttackBonus = 0,
                            CreatedAt = new DateTime(2026, 8, 20, 19, 9, 55, 938, DateTimeKind.Utc).AddTicks(963),
                            DefenseBonus = 3,
                            Description = "Light and agile footwear.",
                            HealthRestore = 0,
                            ManaRestore = 0,
                            MaxStack = 1,
                            Name = "Leather Boots",
                            Rarity = 0,
                            Type = 1,
                            Value = 0
                        });
                });

            modelBuilder.Entity("GameForge.API.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("GameForge.API.Models.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExperienceReward")
                        .HasColumnType("integer");

                    b.Property<Guid?>("GuaranteedItemRewardId")
                        .HasColumnType("uuid");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GuaranteedItemRewardId");

                    b.ToTable("Quests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Clear the cellar of vermin for the local tavernkeeper.",
                            ExperienceReward = 50,
                            GuaranteedItemRewardId = new Guid("44444444-4444-4444-4444-444444444444"),
                            RequiredLevel = 1,
                            Title = "Rats in the Cellar"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Description = "Infiltrate and dismantle the vanguard camp near the forest edge.",
                            ExperienceReward = 150,
                            GuaranteedItemRewardId = new Guid("22222222-2222-2222-2222-222222222222"),
                            RequiredLevel = 2,
                            Title = "The Goblin Outpost"
                        });
                });

            modelBuilder.Entity("GameForge.API.Models.Character", b =>
                {
                    b.HasOne("GameForge.API.Models.Player", "Player")
                        .WithMany("Characters")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameForge.API.Models.InventoryItem", b =>
                {
                    b.HasOne("GameForge.API.Models.Character", "Character")
                        .WithMany("Inventory")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameForge.API.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameForge.API.Models.Item", null)
                        .WithMany("InventoryItems")
                        .HasForeignKey("ItemId1");

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("GameForge.API.Models.Quest", b =>
                {
                    b.HasOne("GameForge.API.Models.Item", "GuaranteedItemReward")
                        .WithMany()
                        .HasForeignKey("GuaranteedItemRewardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GuaranteedItemReward");
                });

            modelBuilder.Entity("GameForge.API.Models.Character", b =>
                {
                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("GameForge.API.Models.Item", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("GameForge.API.Models.Player", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
